version: 0.2
phases:
  pre_build:
    commands:
    - echo Logging in to Amazon ECR...
    - $(aws ecr get-login --no-include-email --region ap-northeast-1)
    - URI=204065533127.dkr.ecr.ap-northeast-1.amazonaws.com
    - VER=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
    - TAG=${VER:=latest}
  build:
    commands:
    - echo Build started on 'date'
    - echo Building the Docker image...
    - docker build -t $URI/jupyter:latest -f Harry_Line/dockerfile/dockerfile-jupyter Harry_Line/dockerfile/
    - docker build -t $URI/api:latest -f Harry_Dev/dockerfile/dockerfile-api Harry_Dev/dockerfile/
    - docker build -t $URI/mysql:latest -f Harry_Dev/dockerfile/dockerfile-mysql Harry_Dev/dockerfile/
    - docker build -t $URI/redis:latest -f Harry_Line/dockerfile/dockerfile-redis Harry_Line/dockerfile/
    - docker tag $URI/jupyter:latest $URI/jupyter:$TAG
    - docker tag $URI/api:latest $URI/api:$TAG
    - docker tag $URI/mysql:latest $URI/mysql:$TAG
    - docker tag $URI/redis:latest $URI/redis:$TAG
  post_build:
    commands:
    - echo Build completed on date
    - echo Pushing the Docker image...
    - docker push $URI/jupyter:latest
    - docker push $URI/api:latest
    - docker push $URI/mysql:latest
    - docker push $URI/redis:latest
    - docker push $URI/jupyter:$TAG
    - docker push $URI/api:$TAG
    - docker push $URI/mysql:$TAG
    - docker push $URI/redis:$TAG
artifacts:
  files:
    - '**/*'
